package dev.kbroom.fluent.codegen.emit

import dev.kbroom.fluent.codegen.KotlinNames
import dev.kbroom.fluent.codegen.model.ArgModel
import dev.kbroom.fluent.codegen.model.AttributeModel
import dev.kbroom.fluent.codegen.model.BundleModel
import dev.kbroom.fluent.codegen.model.GenerateOptions
import dev.kbroom.fluent.codegen.model.MessageModel

/**
 * Emits Kotlin sources for Fluent bundle models.
 */
object KotlinEmitter {
    /**
     * @return map of relative file path → source text
     */
    fun emit(bundles: List<BundleModel>, options: GenerateOptions): Map<String, String> {
        val out = linkedMapOf<String, String>()
        if (options.generateIdConstants) {
            out["FtlIds.kt"] = emitFtlIds(bundles, options.packageName)
        }
        for (bundle in bundles) {
            val pascal = KotlinNames.toPascalCase(bundle.name)
            if (options.generateTypedAccessors) {
                out["${pascal}Messages.kt"] = emitMessagesClass(bundle, options)
                if (options.generateL10n) {
                    out["${pascal}L10n.kt"] = emitL10nClass(bundle, options)
                }
            }
            if (options.generateResourceIds) {
                out["${pascal}Resources.kt"] = emitResources(bundle, options.packageName)
            }
            if (options.generateComposeAccessors && options.generateTypedAccessors) {
                out["${pascal}ComposeAccessors.kt"] = emitComposeAccessors(bundle, options)
            }
        }
        return out
    }

    private fun emitComposeAccessors(bundle: BundleModel, options: GenerateOptions): String {
        val pascal = KotlinNames.toPascalCase(bundle.name)
        val rememberName = "remember${pascal}Messages"
        return buildString {
            appendLine("// Generated by fluent-codegen — do not edit.")
            appendLine("package ${options.packageName}")
            appendLine()
            appendLine("import androidx.compose.runtime.Composable")
            appendLine("import androidx.compose.runtime.remember")
            appendLine("import dev.kbroom.fluent.compose.LocalFluentBundles")
            appendLine()
            appendLine("@Composable")
            appendLine("fun $rememberName(): ${pascal}Messages {")
            appendLine("    val bundle = LocalFluentBundles.current.get(\"${bundle.name}\")")
            appendLine("    return remember(bundle) { ${pascal}Messages(bundle) }")
            appendLine("}")
        }
    }

    private fun emitFtlIds(bundles: List<BundleModel>, packageName: String): String = buildString {
        appendLine("// Generated by fluent-codegen — do not edit.")
        appendLine("package $packageName")
        appendLine()
        appendLine("object FtlIds {")
        for (bundle in bundles) {
            val pascal = KotlinNames.toPascalCase(bundle.name)
            appendLine("    object $pascal {")
            for (message in bundle.messages) {
                val constName = KotlinNames.toConstCase(message.id)
                appendLine("        const val $constName = \"${message.id}\"")
                if (message.attributes.isNotEmpty()) {
                    val attrObj = KotlinNames.toPascalCase(message.id)
                    appendLine("        object $attrObj {")
                    for (attr in message.attributes) {
                        val attrConst = KotlinNames.toConstCase(attr.name)
                        appendLine("            const val $attrConst = \"${attr.name}\"")
                    }
                    appendLine("        }")
                }
            }
            appendLine("    }")
        }
        appendLine("}")
    }

    private fun emitResources(bundle: BundleModel, packageName: String): String {
        val pascal = KotlinNames.toPascalCase(bundle.name)
        return buildString {
            appendLine("// Generated by fluent-codegen — do not edit.")
            appendLine("package $packageName")
            appendLine()
            appendLine("import dev.kbroom.fluent.fallback.ResourceId")
            appendLine("import dev.kbroom.fluent.fallback.ResourceType")
            appendLine()
            appendLine("object ${pascal}Resources {")
            val propNames = mutableListOf<String>()
            val used = mutableSetOf<String>()
            for (path in bundle.resourcePaths) {
                val leaf = path.substringAfterLast('/')
                var candidate = KotlinNames.toPascalCase(leaf)
                var i = 2
                while (!used.add(candidate)) {
                    candidate = "${KotlinNames.toPascalCase(leaf)}$i"
                    i++
                }
                propNames += candidate
                appendLine(
                    "    val $candidate = ResourceId(\"$path\", ResourceType.Required)",
                )
            }
            appendLine("    val All: List<ResourceId> = listOf(${propNames.joinToString(", ")})")
            appendLine("}")
        }
    }

    private fun emitMessagesClass(bundle: BundleModel, options: GenerateOptions): String {
        val pascal = KotlinNames.toPascalCase(bundle.name)
        return buildString {
            appendLine("// Generated by fluent-codegen — do not edit.")
            appendLine("package ${options.packageName}")
            appendLine()
            appendLine("import dev.kbroom.fluent.bundle.FluentBundle")
            appendLine("import dev.kbroom.fluent.bundle.fluentArgsOf")
            appendLine()
            appendLine("class ${pascal}Messages(private val bundle: FluentBundle) {")
            emitMethods(
                sb = this,
                bundle = bundle,
                options = options,
                receiver = "bundle",
                formatMessage = "formatMessage",
                formatAttribute = "formatAttribute",
            )
            appendLine("}")
        }
    }

    private fun emitL10nClass(bundle: BundleModel, options: GenerateOptions): String {
        val pascal = KotlinNames.toPascalCase(bundle.name)
        return buildString {
            appendLine("// Generated by fluent-codegen — do not edit.")
            appendLine("package ${options.packageName}")
            appendLine()
            appendLine("import dev.kbroom.fluent.bundle.fluentArgsOf")
            appendLine("import dev.kbroom.fluent.fallback.Localization")
            appendLine()
            appendLine("class ${pascal}L10n(private val l10n: Localization<*, *, *>) {")
            emitMethods(
                sb = this,
                bundle = bundle,
                options = options,
                receiver = "l10n",
                formatMessage = "format",
                formatAttribute = "formatAttribute",
            )
            appendLine("}")
        }
    }

    private data class EmitTarget(
        val sb: StringBuilder,
        val bundleName: String,
        val options: GenerateOptions,
        val receiver: String,
        val formatMessage: String,
        val formatAttribute: String,
    )

    private fun emitMethods(
        sb: StringBuilder,
        bundle: BundleModel,
        options: GenerateOptions,
        receiver: String,
        formatMessage: String,
        formatAttribute: String,
    ) {
        val target = EmitTarget(sb, bundle.name, options, receiver, formatMessage, formatAttribute)
        val usedNames = mutableSetOf<String>()
        for (message in bundle.messages) {
            if (message.hasValue) {
                val methodName = KotlinNames.uniqueCamel(message.id, usedNames)
                emitMessageMethod(target, message, methodName)
            }
            for (attr in message.attributes) {
                val raw = "${message.id}-${attr.name}"
                val methodName = KotlinNames.uniqueCamel(raw, usedNames)
                emitAttributeMethod(target, message, attr, methodName)
            }
        }
    }

    private fun emitMessageMethod(target: EmitTarget, message: MessageModel, methodName: String) {
        if (target.options.generateKdoc) {
            emitKdoc(target.sb, message.description, message.args)
        }
        val params = paramList(message.args)
        val argsExpr = argsExpression(message.args)
        target.sb.appendLine("    fun $methodName($params): String =")
        if (argsExpr == null) {
            target.sb.appendLine(
                "        ${target.receiver}.${target.formatMessage}(\"${message.id}\")",
            )
        } else {
            target.sb.appendLine(
                "        ${target.receiver}.${target.formatMessage}(\"${message.id}\", $argsExpr)",
            )
        }
        target.sb.appendLine(
            "            ?: error(\"missing message: ${target.bundleName}/${message.id}\")",
        )
        target.sb.appendLine()
    }

    private fun emitAttributeMethod(
        target: EmitTarget,
        message: MessageModel,
        attr: AttributeModel,
        methodName: String,
    ) {
        val description = attr.description.ifBlank {
            "Attribute `${attr.name}` of message `${message.id}`"
        }
        val args = mergeArgLists(message.args, attr.args)
        if (target.options.generateKdoc) {
            emitKdoc(target.sb, description, args)
        }
        val params = paramList(args)
        val argsExpr = argsExpression(args)
        target.sb.appendLine("    fun $methodName($params): String =")
        if (argsExpr == null) {
            target.sb.appendLine(
                "        ${target.receiver}.${target.formatAttribute}(\"${message.id}\", \"${attr.name}\")",
            )
        } else {
            target.sb.appendLine(
                "        ${target.receiver}.${target.formatAttribute}(" +
                    "\"${message.id}\", \"${attr.name}\", $argsExpr)",
            )
        }
        target.sb.appendLine(
            "            ?: error(\"missing attribute: ${target.bundleName}/${message.id}.${attr.name}\")",
        )
        target.sb.appendLine()
    }

    private fun mergeArgLists(a: List<ArgModel>, b: List<ArgModel>): List<ArgModel> {
        val map = linkedMapOf<String, ArgModel>()
        for (arg in a + b) {
            map.putIfAbsent(arg.name, arg)
        }
        return map.values.toList()
    }

    private fun paramList(args: List<ArgModel>): String =
        args.joinToString(", ") { arg ->
            val name = KotlinNames.toCamelCase(arg.name)
            val type = KotlinNames.kotlinType(arg.typeHint)
            "$name: $type"
        }

    private fun argsExpression(args: List<ArgModel>): String? {
        if (args.isEmpty()) return null
        val pairs = args.joinToString(", ") { arg ->
            val param = KotlinNames.toCamelCase(arg.name)
            "\"${arg.name}\" to $param"
        }
        return "fluentArgsOf($pairs)"
    }

    private fun emitKdoc(sb: StringBuilder, description: String, args: List<ArgModel>) {
        val hasBody = description.isNotBlank() || args.any { it.description.isNotBlank() || it.name.isNotBlank() }
        if (!hasBody && args.isEmpty()) return
        sb.appendLine("    /**")
        if (description.isNotBlank()) {
            for (line in description.lines()) {
                sb.appendLine("     * ${escapeKdoc(line)}")
            }
            if (args.isNotEmpty()) sb.appendLine("     *")
        }
        for (arg in args) {
            val paramName = KotlinNames.toCamelCase(arg.name).removeSurrounding("`")
            val desc = buildString {
                if (arg.typeHint.isNotBlank()) append("(${arg.typeHint}) ")
                append(arg.description)
            }.trim()
            if (desc.isEmpty()) {
                sb.appendLine("     * @param $paramName")
            } else {
                sb.appendLine("     * @param $paramName ${escapeKdoc(desc)}")
            }
        }
        sb.appendLine("     */")
    }

    private fun escapeKdoc(text: String): String =
        text.replace("*/", "*∕").replace(Regex("(?m)^\\*"), "⁎")
}
